version: '3.8'

services:
  database:
    image: mysql:8.0
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: database
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/symfony:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - 80:80
  php:
    build: docker/php-fpm
    volumes:
      - ./:/var/www/symfony:cached
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - database
  composer:
    image: composer:latest
    command: install
    volumes:
      - .:/app
  node:
    image: node:12-alpine
    volumes:
      - .:/app:cached
    working_dir: /app
