---
- hosts: all
  any_errors_fatal: true
  vars_files:
    - vars.yml
  tasks:
    - block:
        - include_role:
            name: "cbrunnkvist.ansistrano-symfony-deploy"
      rescue:
        - name: ROLLBACK | Fetch stat of current symlink
          stat:
            path: "{{ ansistrano_deploy_to }}/{{ ansistrano_current_dir }}"
          register: stat_current_link
        - name: ROLLBACK | Remove not fully deployed release
          file:
            state: absent
            path: "{{ ansistrano_release_path.stdout }}"
          when: >
            (stat_current_link.stat.islnk is not defined)
            or
            (ansistrano_release_path.stdout != stat_current_link.stat.lnk_source)
        - name: ROLLBACK | Force Ansible to return an exit code error
          fail:
            msg: "Something gone wrong during deployment, refer to logs."
