name: Deployment

on:
  push:
    branches: [ feat/deploy-raspberry ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        version: 14.x

    - name: Install dependencies
      run: |
        composer install --no-dev --no-progress --prefer-dist --optimize-autoloader
        yarn install --production --check-files

    - name: Sync
      env:
        dest: "${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/yannlefresne.tech"
      run: |
        echo "${{secrets.KEY}}" > deploy_key
        chmod 600 ./deploy_key
        rsync -chav --delete \
          -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
          --exclude /deploy_key \
          --exclude /.git/ \
          --exclude /.github/ \
          --exclude /.env \
          --exclude /var/ \
          --exclude /docker/ \
          --exclude /docker-compose.yaml \
          --exclude /Makefile \
          ./ ${{env.dest}}

    - name: Run migrations & Warm up cache
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /var/www/yannlefresne.tech/
          php bin/console --no-interaction d:m:m
          php bin/console cache:warmup
