name: Greetings

on: [pull_request, issues]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: actions/check-commiter
      id: contributor
      uses: ./.github/actions/check-commiter
      with:
        URL: ${{ github.event.repository.contributors_url }}
        COMMITER: ${{ github.actor }}
    - uses: actions/first-interaction@v1
      if: ${{ github.actor != github.repository_owner && steps.contributor.outputs.result }}
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for your contribution and this first issue !'
        pr-message: 'Thanks for this work and this first PR !'
